---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
type: servicebinding.io/redis
stringData:
  type: "redis"
  provider: "redis"
  host: "demo-db"
  port: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-db
spec:
  ports:
    - port: 6379
  selector:
    app: demo-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db
  labels:
    app: demo-db
spec:
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - image: redis:7.2
          name: redis
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
              name: redis
          livenessProbe:
            tcpSocket:
              port: redis
          readinessProbe:
            tcpSocket:
              port: redis
          startupProbe:
            tcpSocket:
              port: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
